[package]
name = "tabular_core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Core tabular data types used in egui_tabular"

[dependencies]
rvariant = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
strum = { workspace = true }
