use convert_case::{Case, Casing};
use proc_macro2::{Ident, Span, TokenStream};
use quote::quote;
use syn::spanned::Spanned;
use syn::{Expr, ExprLit, Field, Index, ItemStruct, Lit, LitInt, LitStr, Member, Meta};

pub(super) fn tabular_row(struct_def: TokenStream) -> TokenStream {
    let struct_def = match syn::parse2::<ItemStruct>(struct_def) {
        Ok(s) => s,
        Err(e) => return e.to_compile_error(),
    };
    let fields: Vec<FieldInfo> = match struct_def
        .fields
        .iter()
        .enumerate()
        .map(|(idx, field)| FieldInfo::new(idx, field))
        .collect()
    {
        Ok(fields) => fields,
        Err(e) => return e.to_compile_error(),
    };

    let vis = &struct_def.vis;
    let row_ident = &struct_def.ident;
    let table_ident = Ident::new(&format!("{row_ident}Table"), row_ident.span());
    let doc = format!(
        "Read-only [`TableModel`](egui_tabular::TableModel) over a `Vec<{row_ident}>`, generated by `#[derive(TabularRow)]`. \
         Row uids are row indices."
    );

    let columns = fields.iter().map(|f| {
        let (uid, name, ty) = (&f.uid, &f.name, &f.ty_label);
        quote! {
            (
                egui_tabular::ColumnUid(#uid),
                egui_tabular::ColumnInfo::new(#name, None).type_label(#ty),
            )
        }
    });
    let cell_arms = fields.iter().map(|f| {
        let (uid, value) = (&f.uid, &f.value);
        quote! { #uid => #value, }
    });

    quote! {
        #[doc = #doc]
        #vis struct #table_ident {
            data: Vec<#row_ident>,
            columns: Vec<(egui_tabular::ColumnUid, egui_tabular::ColumnInfo)>,
            revision: egui_tabular::Revision,
        }

        #[allow(dead_code)]
        impl #table_ident {
            pub fn new(data: Vec<#row_ident>) -> Self {
                Self {
                    data,
                    columns: vec![#(#columns),*],
                    revision: egui_tabular::Revision::default(),
                }
            }

            pub fn data(&self) -> &[#row_ident] {
                &self.data
            }

            /// Mutable access to the rows. Counts as a change of all rows and cells.
            pub fn data_mut(&mut self) -> &mut Vec<#row_ident> {
                self.revision.rows += 1;
                self.revision.cells += 1;
                &mut self.data
            }

            fn cell_value(row: &#row_ident, col: u32) -> Option<egui_tabular::rvariant::Variant> {
                #[allow(unused_imports)]
                use egui_tabular::__derive::{ViaDebug as _, ViaInto as _};
                Some(match col {
                    #(#cell_arms)*
                    _ => return None,
                })
            }
        }

        impl egui_tabular::TableModel for #table_ident {
            fn revision(&self) -> egui_tabular::Revision {
                self.revision
            }

            fn capabilities(&self) -> egui_tabular::Capabilities {
                egui_tabular::Capabilities::NONE
            }

            fn columns(&self) -> impl Iterator<Item = egui_tabular::ColumnUid> {
                self.columns.iter().map(|(uid, _)| *uid)
            }

            fn column(&self, col: egui_tabular::ColumnUid) -> Option<&egui_tabular::ColumnInfo> {
                self.columns
                    .iter()
                    .find(|(uid, _)| *uid == col)
                    .map(|(_, info)| info)
            }

            fn rows(&self) -> impl Iterator<Item = egui_tabular::RowUid> {
                (0..self.data.len() as u64).map(egui_tabular::RowUid)
            }

            fn row_count(&self) -> usize {
                self.data.len()
            }

            fn get(
                &self,
                coord: egui_tabular::CellCoord,
            ) -> Option<::std::borrow::Cow<'_, egui_tabular::rvariant::Variant>> {
                let row = self.data.get(coord.row_uid.0 as usize)?;
                Self::cell_value(row, coord.col_uid.0).map(::std::borrow::Cow::Owned)
            }

            fn row_values(
                &self,
                row: egui_tabular::RowUid,
                cols: &[egui_tabular::ColumnUid],
                out: &mut Vec<Option<egui_tabular::rvariant::Variant>>,
            ) {
                let row = self.data.get(row.0 as usize);
                out.extend(
                    cols.iter()
                        .map(|col| row.and_then(|row| Self::cell_value(row, col.0))),
                );
            }
        }
    }
}

struct FieldInfo {
    uid: LitInt,
    name: String,
    ty_label: String,
    /// Expression turning `row.<field>` into a `Variant`.
    value: TokenStream,
}

impl FieldInfo {
    fn new(idx: usize, field: &Field) -> syn::Result<Self> {
        let span = field.span();
        let (member, name) = match &field.ident {
            Some(ident) => (
                Member::Named(ident.clone()),
                ident.to_string().to_case(Case::Sentence),
            ),
            None => (
                Member::Unnamed(Index {
                    index: idx as u32,
                    span,
                }),
                idx.to_string(),
            ),
        };
        let ty = &field.ty;
        let value = match format_attr(field)? {
            Some(format) => quote! {
                egui_tabular::rvariant::Variant::Str(format!(#format, row.#member))
            },
            // `Into<Variant>` if the field type has it, otherwise its `Debug` text.
            None => quote! {
                (&&egui_tabular::__derive::Wrap(&row.#member)).to_variant()
            },
        };
        Ok(FieldInfo {
            uid: LitInt::new(&idx.to_string(), Span::call_site()),
            name,
            ty_label: quote!(#ty).to_string(),
            value,
        })
    }
}

/// The string of `#[format = "..."]`, if present.
fn format_attr(field: &Field) -> syn::Result<Option<LitStr>> {
    for attr in &field.attrs {
        let Meta::NameValue(name_value) = &attr.meta else {
            continue;
        };
        if !name_value.path.is_ident("format") {
            continue;
        }
        return match &name_value.value {
            Expr::Lit(ExprLit {
                lit: Lit::Str(format),
                ..
            }) => Ok(Some(format.clone())),
            other => Err(syn::Error::new(
                other.span(),
                "expected a format string, e.g. #[format = \"0x{:08x}\"]",
            )),
        };
    }
    Ok(None)
}
