[package]
name = "egui_tabular"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "tabular_core",
    "tabular_derive",
    "demos/*", "tests",
]

[workspace.dependencies]
rvariant = { path = "../rvariant", features = ["serde"] }
strum = { version = "0.28", features = ["derive"] }
egui = { version = "0.33" }
eframe = { version = "0.33", features = ["serde", "persistence"] }

[dependencies]
egui.workspace = true
egui_extras = { version = "0.33", features = ["serde"] }
#egui-modal = { version = "0.6" }
#egui-phosphor = { version = "0.7", features = ["fill"] }
itertools = "0.14"
rfd = "0.17"
log = "0"
serde = { version = "1", features = ["derive"] }
csv = "1.3"
strum = { workspace = true }
tap = "1.0"
tabular_core = { path = "./tabular_core" }
tabular_derive = { path = "./tabular_derive" }
chardetng = "0.1"
encoding_rs = "0.8"
encoding_rs_io = "0.1"
rvariant = { workspace = true }
indexmap = "2"
