[package]
name = "tabular_derive"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Procedural macro for deriving tabular data types used in egui_tabular"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.11"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
